-- init db

-- changeset elena 05-12-2024-1
CREATE SEQUENCE IF NOT EXISTS category_id_seq START WITH 1 INCREMENT BY 1;

-- changeset elena 05-12-2024-2
CREATE SEQUENCE IF NOT EXISTS category_id_seq1 START WITH 1 INCREMENT BY 1;

-- changeset elena 05-12-2024-3
CREATE SEQUENCE IF NOT EXISTS competition_id_seq START WITH 1 INCREMENT BY 1;

-- changeset elena 05-12-2024-4
CREATE SEQUENCE IF NOT EXISTS competition_id_seq1 START WITH 1 INCREMENT BY 1;

-- changeset elena 05-12-2024-5
CREATE SEQUENCE IF NOT EXISTS criteria_id_seq START WITH 1 INCREMENT BY 1;

-- changeset elena 05-12-2024-6
CREATE SEQUENCE IF NOT EXISTS criteria_id_seq1 START WITH 1 INCREMENT BY 1;

-- changeset elena 05-12-2024-7
CREATE SEQUENCE IF NOT EXISTS judge_id_seq START WITH 1 INCREMENT BY 1;

-- changeset elena 05-12-2024-8
CREATE SEQUENCE IF NOT EXISTS judge_id_seq1 START WITH 1 INCREMENT BY 1;

-- changeset elena 05-12-2024-9
CREATE SEQUENCE IF NOT EXISTS member_id_seq START WITH 1 INCREMENT BY 1;

-- changeset elena 05-12-2024-10
CREATE SEQUENCE IF NOT EXISTS member_id_seq1 START WITH 1 INCREMENT BY 1;

-- changeset elena 05-12-2024-11
CREATE SEQUENCE IF NOT EXISTS rating_id_seq START WITH 1 INCREMENT BY 1;

-- changeset elena 05-12-2024-12
CREATE SEQUENCE IF NOT EXISTS rating_id_seq1 START WITH 1 INCREMENT BY 1;

-- changeset elena 05-12-2024-13
CREATE SEQUENCE IF NOT EXISTS round_id_seq START WITH 1 INCREMENT BY 1;

-- changeset elena 05-12-2024-14
CREATE SEQUENCE IF NOT EXISTS round_id_seq1 START WITH 1 INCREMENT BY 1;

-- changeset elena 05-12-2024-15
CREATE SEQUENCE IF NOT EXISTS user_id_seq START WITH 1 INCREMENT BY 1;

-- changeset elena 05-12-2024-16
CREATE SEQUENCE IF NOT EXISTS user_id_seq1 START WITH 1 INCREMENT BY 1;

-- changeset elena 05-12-2024-17
CREATE SEQUENCE IF NOT EXISTS user_user_id_seq START WITH 1 INCREMENT BY 1;

-- changeset elena 05-12-2024-18
CREATE SEQUENCE IF NOT EXISTS user_user_id_seq1 START WITH 1 INCREMENT BY 1;

-- changeset elena 05-12-2024-19
CREATE SEQUENCE IF NOT EXISTS users_id_seq START WITH 1 INCREMENT BY 1;

-- changeset elena 05-12-2024-20
CREATE TABLE category
(
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    modified_at TIMESTAMP WITHOUT TIME ZONE,
    category    VARCHAR(255)                            NOT NULL,
    created_by  VARCHAR(255),
    modified_by VARCHAR(255),
    CONSTRAINT category_pk PRIMARY KEY (id)
);

-- changeset elena 05-12-2024-21
CREATE TABLE competition
(
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    modified_at TIMESTAMP WITHOUT TIME ZONE,
    start_date  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_by  VARCHAR(255),
    description VARCHAR(255),
    modified_by VARCHAR(255),
    name        VARCHAR(255)                            NOT NULL,
    CONSTRAINT competition_pk PRIMARY KEY (id)
);

-- changeset elena 05-12-2024-22
CREATE TABLE criteria
(
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    modified_at TIMESTAMP WITHOUT TIME ZONE,
    created_by  VARCHAR(255),
    criteria    VARCHAR(255)                            NOT NULL,
    modified_by VARCHAR(255),
    CONSTRAINT criteria_pk PRIMARY KEY (id)
);

-- changeset elena 05-12-2024-23
CREATE TABLE judge
(
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    modified_at TIMESTAMP WITHOUT TIME ZONE,
    users_id    BIGINT,
    city        VARCHAR(255),
    club        VARCHAR(255),
    country     VARCHAR(255),
    created_by  VARCHAR(255),
    modified_by VARCHAR(255),
    name        VARCHAR(255),
    phone       VARCHAR(255),
    second_name VARCHAR(255),
    surname     VARCHAR(255),
    CONSTRAINT judge_pk PRIMARY KEY (id)
);

-- changeset elena 05-12-2024-24
CREATE TABLE judges_to_competition
(
    competition_id BIGINT NOT NULL,
    judge_id       BIGINT NOT NULL
);

-- changeset elena 05-12-2024-25
CREATE TABLE member
(
    category_id    BIGINT,
    competition_id BIGINT,
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    modified_at    TIMESTAMP WITHOUT TIME ZONE,
    city           VARCHAR(255),
    club           VARCHAR(255),
    country        VARCHAR(255),
    created_by     VARCHAR(255),
    modified_by    VARCHAR(255),
    name           VARCHAR(255),
    phone          VARCHAR(255),
    second_name    VARCHAR(255),
    surname        VARCHAR(255),
    CONSTRAINT member_pk PRIMARY KEY (id)
);

-- changeset elena 05-12-2024-26
CREATE TABLE rating
(
    rating         INTEGER,
    category_id    BIGINT,
    competition_id BIGINT,
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    criteria_id    BIGINT,
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    judge_id       BIGINT,
    member_id      BIGINT,
    modified_at    TIMESTAMP WITHOUT TIME ZONE,
    round_id       BIGINT,
    created_by     VARCHAR(255),
    modified_by    VARCHAR(255),
    CONSTRAINT rating_pk PRIMARY KEY (id)
);

-- changeset elena 05-12-2024-27
CREATE TABLE round
(
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    modified_at TIMESTAMP WITHOUT TIME ZONE,
    created_by  VARCHAR(255),
    modified_by VARCHAR(255),
    round       VARCHAR(255)                            NOT NULL,
    CONSTRAINT round_pk PRIMARY KEY (id)
);

-- changeset elena 05-12-2024-28
CREATE TABLE users
(
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    modified_at TIMESTAMP WITHOUT TIME ZONE,
    created_by  VARCHAR(255),
    modified_by VARCHAR(255),
    password    VARCHAR(255)                            NOT NULL,
    role        VARCHAR(255)                            NOT NULL,
    username    VARCHAR(255)                            NOT NULL,
    CONSTRAINT users_pk PRIMARY KEY (id)
);

-- changeset elena 05-12-2024-29
ALTER TABLE category
    ADD CONSTRAINT category_category_key UNIQUE (category);

-- changeset elena 05-12-2024-30
ALTER TABLE criteria
    ADD CONSTRAINT criteria_criteria_key UNIQUE (criteria);

-- changeset elena 05-12-2024-31
ALTER TABLE judge
    ADD CONSTRAINT judge_users_id_key UNIQUE (users_id);

-- changeset elena 05-12-2024-32
ALTER TABLE round
    ADD CONSTRAINT round_round_key UNIQUE (round);

-- changeset elena 05-12-2024-33
ALTER TABLE users
    ADD CONSTRAINT users_username_key UNIQUE (username);

-- changeset elena 05-12-2024-34
ALTER TABLE judges_to_competition
    ADD CONSTRAINT judges_to_comp_judge_id_fk FOREIGN KEY (judge_id) REFERENCES judge (id) ON DELETE NO ACTION;

-- changeset elena 05-12-2024-35
ALTER TABLE judges_to_competition
    ADD CONSTRAINT judges_to_comp_comp_id_fk FOREIGN KEY (competition_id) REFERENCES competition (id) ON DELETE NO ACTION;

-- changeset elena 05-12-2024-36
ALTER TABLE rating
    ADD CONSTRAINT rating_criteria_id_fk FOREIGN KEY (criteria_id) REFERENCES criteria (id) ON DELETE NO ACTION;

-- changeset elena 05-12-2024-37
ALTER TABLE rating
    ADD CONSTRAINT rating_member_id_fk FOREIGN KEY (member_id) REFERENCES member (id) ON DELETE NO ACTION;

-- changeset elena 05-12-2024-38
ALTER TABLE rating
    ADD CONSTRAINT rating_cat_id_fk FOREIGN KEY (category_id) REFERENCES category (id) ON DELETE NO ACTION;

-- changeset elena 05-12-2024-39
ALTER TABLE rating
    ADD CONSTRAINT rating_round_id_fk FOREIGN KEY (round_id) REFERENCES round (id) ON DELETE NO ACTION;

-- changeset elena 05-12-2024-40
ALTER TABLE rating
    ADD CONSTRAINT rating_comp_id_fk FOREIGN KEY (competition_id) REFERENCES competition (id) ON DELETE NO ACTION;

-- changeset elena 05-12-2024-41
ALTER TABLE rating
    ADD CONSTRAINT rating_judge_id_fk FOREIGN KEY (judge_id) REFERENCES judge (id) ON DELETE NO ACTION;

-- changeset elena 05-12-2024-42
ALTER TABLE member
    ADD CONSTRAINT member_comp_id_fk FOREIGN KEY (competition_id) REFERENCES competition (id) ON DELETE NO ACTION;

-- changeset elena 05-12-2024-43
ALTER TABLE member
    ADD CONSTRAINT member_category_id_fk FOREIGN KEY (category_id) REFERENCES category (id) ON DELETE NO ACTION;

-- changeset elena 05-12-2024-44
ALTER TABLE judge
    ADD CONSTRAINT judge_users_id_fk FOREIGN KEY (users_id) REFERENCES users (id) ON DELETE NO ACTION;

