spring:
  application:
    name: jack-and-jill
  datasource:
    url: jdbc:postgresql://localhost:9432/jack_and_jill
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show-sql: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    default-schema: jack

app:
  swagger-ui:
    api-version: 1.0
    api-title: 'jack and jill'
    api-description: 'api for jack and jill application'
    contact-name: Elena
    contact-email: email.email.com