spring:
  application:
    name: jackjill
  datasource:
    url: jdbc:h2:mem:jack_and_jill_db
    driverClassName: org.h2.Driver
    username: admin
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show-sql: true
